name: Daily Model Training

on:
  schedule:
    - cron: '30 16 * * *'  # Runs at 16:30 UTC every day

jobs:
  train-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Configure Poetry
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install

      - name: Fetch data
        run: |
          poetry run python backend/IE-app/scripts/fetch_data.py

      - name: Preprocess data
        run: |
          poetry run python backend/IE-app/scripts/preprocess_data.py

      - name: Train model
        run: |
          poetry run python backend/IE-app/scripts/train_model.py

      - name: DVC Add data and models
        run: |
          poetry run dvc add backend/IE-app/data
          poetry run dvc add backend/IE-app/models

      - name: DVC Push
        run: |
          poetry run dvc push -r origin

      - name: Git operations
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add .
          git commit -m "My daily workflow pipeline"
          git push
